enum EpochType {
  DAY
  WEEK
  MONTH
}

type AggregateTradingStats @entity {
  "Address-type-number"
  id: ID!

  "Epoch Type"
  epochType: EpochType!

  "Epoch Number"
  epochNumber: Int!

  "Total Volume"
  totalVolume: BigDecimal!

  "Total Open Fees"
  totalOpenFees: BigDecimal!

  "Total Close Fees"
  totalCloseFees: BigDecimal!

  "Total Borrowing Fees"
  totalBorrowingFees: BigDecimal!

  "Total Trades"
  totalTrades: Int!

  "Pairs Traded"
  pairsTraded: [Int!]!

  "Total PnL"
  totalPnl: BigDecimal!

  "Total PnL Percentage"
  totalPnlPercentage: BigDecimal!
}
