enum EpochType {
  DAY
  WEEK
  MONTH
}

type AggregateTradingStats @entity {
  "Address-type-number"
  id: ID!

  "Address"
  address: String!

  "Epoch Type"
  epochType: EpochType!

  "Epoch Number"
  epochNumber: Int!

  "Total Volume"
  totalVolumePerGroup: [BigDecimal!]!

  "Total open fees"
  totalOpenFees: BigDecimal!

  "Total close fees"
  totalCloseFees: BigDecimal!

  "Total borrowing fees"
  totalBorrowingFees: BigDecimal!

  "Pairs Traded"
  pairsTraded: [Int!]!

  "Total PnL"
  totalPnl: BigDecimal!

  "Total PnL Percentage"
  totalPnlPercentage: BigDecimal!
}
