enum EpochType {
  day
  week
}

type AggregateTradingStat @entity {
  "Address-type-number"
  id: ID!

  "Address"
  address: String!

  "Epoch Type"
  epochType: EpochType!

  "Epoch Number"
  epochNumber: Int!

  "Total Volume"
  totalVolumePerGroup: [BigDecimal!]!

  "Total borrowing fees"
  totalBorrowingFees: BigDecimal!

  "Pairs Traded"
  pairsTraded: [Int!]!

  "Total PnL"
  totalPnl: BigDecimal!

  "Total PnL Percentage"
  totalPnlPercentage: BigDecimal!

  "Total gov fees"
  totalGovFees: BigDecimal!

  "Total referral fees"
  totalReferralFees: BigDecimal!

  "Total trigger fees"
  totalTriggerFees: BigDecimal!

  "Total staker fees"
  totalStakerFees: BigDecimal!

  "Total lp fees"
  totalLpFees: BigDecimal!
}

type UserPointStat @entity {
  "Address-epochType-epochNumber"
  id: ID!
  address: String!
  epochNumber: Int!
  epochType: EpochType!
  totalFeesPaid: BigDecimal!
  pnl: BigDecimal!
  pnlPercentage: BigDecimal!
  groupsTraded: [BigDecimal!]!
  loyaltyPoints: BigDecimal!
  volumePoints: BigDecimal!
  skillPoints: BigDecimal!
  diversityPoints:BigDecimal!
  totalPoints: BigDecimal!
}
