sources:
  - name: gtrade-stats
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/gainsnetwork-org/{context.graphName:gtrade-stats-arbitrum-v3}
        retry: 3
    transforms:
      - autoPagination:
          validateSchema: false
          limitOfRecords: 5000

  - name: gtoken
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/thebuidler/{context.graphName:gtoken-arbitrum-mc1}
        retry: 3

additionalTypeDefs: |
  # Types
  type RewardDistributionP {
    loyalty: Float!
    fee: Float!
    absSkill: Float!
    relSkill: Float!
    diversity: Float!
  }

  type EpochRewardDistributionP {
    startEpoch: Int!
    endEpoch: Int!
    rewardDistribution: RewardDistributionP!
  }

  type RewardConfig {
    id: ID!
    active: Boolean!
    totalRewards: Int!
    epochType: EpochType!
    numEpochs: Int!
    startingEpoch: Int!
    rewardDistribution: RewardDistributionP!
    rewardDistributionOverrides: [EpochRewardDistributionP!]!
    rewardsPairIx: Int
    capFeeRewards: Boolean
  }

  type RewardResults {
    address: String!
    total: Float!
    loyalty: Float!
    fee: Float!
    absSkill: Float!
    relSkill: Float!
    diversity: Float!
    loyaltyPoints: Float!
    feePoints: Float!
    absSkillPoints: Float!
    relSkillPoints: Float!
    diversityPoints: Float!
  }

  # Query extensions
  extend type Query {
    getActiveRewardConfigs: [RewardConfig!]!
    getRewardConfig(id: ID!): RewardConfig
    getAddressRewardsForEpoch(address: String!, rewardConfigId: ID!, epoch: Int!, rewardToUsd: Float): RewardResults!
    getAllRewardsForEpoch(rewardConfigId: ID!, epoch: Int!, rewardToUsd: Float): [RewardResults!]!
    getAllRewardsForLastEpoch(rewardConfigId: ID!, rewardToUsd: Float): [RewardResults!]!
  }

additionalResolvers:
  - ./resolvers/index.js

documents:
  - ./queries/*.gql

codegen:
  contextType: "MeshContext & { chainId: string; graphName: string; }"
