sources:
  - name: gtrade-stats
    handler:
      graphql:
        endpoint: https://{context.subgraphEndpoint:gateway-arbitrum.network.thegraph.com/api/34948ca8a5e572dddca38d54943c693c/subgraphs/id/EJeTLXXHku65Xa1UFtHNFdQfiEPKAcrc9qGCruEU4WMr}
        retry: 3

    transforms:
      - autoPagination:
          validateSchema: false
          limitOfRecords: 5000

  - name: gtoken
    handler:
      graphql:
        endpoint: https://{context.subgraphEndpoint:gateway-arbitrum.network.thegraph.com/api/34948ca8a5e572dddca38d54943c693c/subgraphs/id/J9WvpchpS1Sd5fQ4t7grJgMeC3nFTgHuJJe88YnkoaPF}
        retry: 3

additionalTypeDefs: |
  # Types
  type RewardDistributionP {
    loyalty: Float!
    fee: Float!
    absSkill: Float!
    relSkill: Float!
    diversity: Float!
    total: Float
  }

  type EpochRewardDistributionP {
    startEpoch: Int!
    endEpoch: Int!
    rewardDistribution: RewardDistributionP!
  }

  type RewardConfig {
    id: ID!
    active: Boolean!
    totalRewards: Int!
    epochType: EpochType!
    numEpochs: Int!
    startingEpoch: Int!
    rewardDistribution: RewardDistributionP!
    rewardDistributionOverrides: [EpochRewardDistributionP!]!
    rewardsPairIx: Int
    capFeeRewards: Boolean
  }

  type RewardResults {
    address: String!
    total: Float!
    loyalty: Float!
    fee: Float!
    absSkill: Float!
    relSkill: Float!
    diversity: Float!
    loyaltyPoints: Float!
    feePoints: Float!
    absSkillPoints: Float!
    relSkillPoints: Float!
    diversityPoints: Float!
  }

  # Query extensions
  extend type Query {
    getActiveRewardConfigs: [RewardConfig!]!
    getRewardConfig(id: ID!): RewardConfig
    getAddressRewardsForEpoch(address: String!, rewardConfigId: ID!, epoch: Int!, rewardToUsd: Float): RewardResults!
    getAllRewardsForEpoch(rewardConfigId: ID!, epoch: Int!, rewardToUsd: Float): [RewardResults!]!
    getAllRewardsForLastEpoch(rewardConfigId: ID!, rewardToUsd: Float): [RewardResults!]!
  }

additionalResolvers:
  - ./resolvers/index.js

documents:
  - ./queries/*.gql

codegen:
  contextType: "MeshContext & { chainId: string; graphName: string; apiKey: string; subgraphEndpoint: string; }"
